In [1]:
name = "城西太郎"
age = 60
print(f"私の名前は{name}で, {age}歳です。")

私の名前は城西太郎で, 60歳です。


In [2]:
x = 10
y = 20
print(f"{x} + {y} = {x + y}")

10 + 20 = 30


In [9]:
squares = [i**2 for i in range(10)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
squares = [i**2 for i in range(11)]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [11]:
squares = [i**3 for i in range(11)]
print(squares)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [12]:
squares = [i**4 for i in range(11)]
print(squares)

[0, 1, 16, 81, 256, 625, 1296, 2401, 4096, 6561, 10000]


In [13]:
odds = [i for i in range(10) if i % 2 == 1]
print(odds)

[1, 3, 5, 7, 9]


In [19]:
squares = tuple(i**2 for i in range(10))
print(squares)

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)


In [20]:
import numpy as np
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])
print(data)

[ 9  2  3  4 10  6  7  8  1  5]


In [22]:
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6], ])
print(data)

[[1 2 3]
 [4 5 6]]


In [23]:
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
print("掛け算", np.array([1, 2, 3, 4, 5])*np.array([6, 7, 8, 9, 10]))
print("累乗", np.array([1, 2, 3, 4, 5])**2)
print("割り算", np.array([1, 2, 3, 4, 5])/np.array([10, 10, 10, 10, 10]))

掛け算 [ 6 14 24 36 50]
累乗 [ 1  4  9 16 25]
割り算 [0.1 0.2 0.3 0.4 0.5]


In [27]:
deta = np.array([120, 180, 300, 150])
print(np.sum(deta))
print(np.product(deta))
print(np.square(deta))
print(np.mean(deta))
print(np.min(deta))
print(np.max(deta))
print(np.argmin(deta))
print(np.argmax(deta))

750
972000000
[14400 32400 90000 22500]
187.5
120
300
0
2


In [41]:
deta = np.array([120, 180, 300, 150])
print(np.sort(deta))
print(np.sort(deta)[::-1])
print(np.argsort(deta))
print(np.argsort(deta)[::-1])
print(np.unique(deta))
print(np.unique(deta)[::-1])

[120 150 180 300]
[300 180 150 120]
[0 3 1 2]
[2 1 3 0]
[120 150 180 300]
[300 180 150 120]


In [42]:
deta = np.array([120, 180, 300, 150])
print(np.where(data>150))

(array([], dtype=int64), array([], dtype=int64))


In [3]:
import numpy as np
deta = np.array([120, 180, 300, 150])
data1 = np.array([120, 180])
data2 = np.array([300, 150])
np.concatenate([data1, data2])

array([120, 180, 300, 150])

In [38]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])