In [2]:
import numpy as np
w = np.array([[5.0], [3.0]])

x = np.array([[1.0, 5.0]])

print(w)
print(x)

[[5.]
 [3.]]
[[1. 5.]]


In [4]:
zeros = np.zeros([1, 5])
ones = np.ones([1, 5])

print(zeros)
print(ones)

[[0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [5]:
uniform = np.random.rand(1, 5)
normal = np.random.normal(size = [1, 5])

print(uniform)
print(normal)

[[0.68936855 0.13381885 0.33621222 0.36979926 0.6322619 ]]
[[ 0.20196032  0.90632286  0.59223141  0.04162025 -1.58805863]]


In [6]:
x = np.array([1, 2])
y = np.array([3, 4])

print(x)
print(y)
np.dot(x, y)

[1 2]
[3 4]


11

In [7]:
x = np.array([1, 1])
y = np.array([1, -1])

print(x)
print(y)
np.dot(x, y)

[1 1]
[ 1 -1]


0

In [8]:
x = np.array([[1.0, 5.0]])
y = np.array([[5.0], [3.0]])

xy = np.matmul(x, y)

print(x)
print(y)
print(xy)

[[1. 5.]]
[[5.]
 [3.]]
[[20.]]


In [9]:
x = np.array([[-1.0, -1.0]])
y = np.array([[1.0], [-1.0]])

xy = np.matmul(x, y)

print(x)
print(y)
print(xy)

[[-1. -1.]]
[[ 1.]
 [-1.]]
[[0.]]


In [11]:
x = np.array([[1.0, 5.0]])
y = np.array([[5.0, 3.0]])

xy = np.matmul(x, y.T)

print(x)
print(y)
print(xy)

[[1. 5.]]
[[5. 3.]]
[[20.]]


In [12]:
X = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])
w = np.array([[5.0], [3.0]])
b = np.array([[1.0], [1.0], [1.0]])

Xwb = np.matmul(X, w) + b

print(Xwb)

[[12.]
 [23.]
 [34.]]


In [17]:
print(X)

[[1. 2.]
 [2. 4.]
 [3. 6.]]


In [18]:
print(w)

[[5.]
 [3.]]


In [19]:
print(b)

[[1.]
 [1.]
 [1.]]


In [20]:
A = np.array([[6.0, 2.0], [2.0, 5.0]])
rankA = np.linalg.matrix_rank(A)

print(rankA)

2


In [25]:
B = np.array([[6.0, 2.0, 4.0], [2.0, 5.0, 2.0], [3.0, 5.0, 1.0]])
rankB = np.linalg.matrix_rank(B)

print(rankB)

3


In [26]:
A = np.array([[6.0, 2.0], [2.0, 5.0]])

invA = np.linalg.inv(A)

print(invA)

[[ 0.19230769 -0.07692308]
 [-0.07692308  0.23076923]]


In [27]:
A = np.array([[6.0, 2.0], [2.0, 5.0]])
B = np.array([[6.0, 3.0], [2.0, 1.0]])

detA = np.linalg.det(A)
detB = np.linalg.det(B)

print(detA)
print(detB)

25.99999999999999
3.330669073875464e-16


In [28]:
A = np.array([[6.0, 2.0], [2.0, 5.0]])
B = np.array([[6.0, 3.0], [2.0, 1.0]])

detA = np.linalg.det(A)
detB = np.linalg.det(B)

print(f"Determinant A : {detA: 1f}")
print(f"Determinant B : {detB: 1f}")

Determinant A :  26.000000
Determinant B :  0.000000


In [30]:
A = np.array([[3.0, 2.0], [4.0, 1.0]])

E, V = np.linalg.eig(A)

print(f"Eigenvalue :\n {E}")
print(f"Eigenvector :\n {V}")

Eigenvalue :
 [ 5. -1.]
Eigenvector :
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [31]:
A = np.array([[2, -3], [4, 1]])

b = np.array([5], [-2])

if np.linalg.det(A != 0:
    w = np.matmul(np.linalg.inv(A), b)
    print(f"Solution \n {w}")
else:
    print(f"No soolution.")

SyntaxError: invalid syntax (410810304.py, line 5)